### PR TITLE
chore: modifie README.md

### PR DESCRIPTION
**Pull request by roolrd**

### CODE REVIEW

**Review by rr-epam — APPROVED** [review]

**Review by rr-epam — COMMENTED** [review]
looks nice

**Review by rr-epam — APPROVED** [review]

**Comment by rr-epam** [comment]
looks nice

**Review by roolrd — COMMENTED** [review]
+

**Review by roolrd — COMMENTED** [review]
++

**Comment by roolrd** [comment]
This PR is included in version 1.0.0 :tada:

**Pull request merged**
